### ISSUE TITLE
这个开发环境怎么配

### ISSUE THREAD

**Issue by zzw12** [cloudreve/frontend#1]

**Comment by HFO4** [comment]
安装`npm`后直接`npm install`然后`npm start`

**Comment by zzw12** [comment]
start 之后 HTML文件里的数据从哪来呢

**Comment by zzw12** [comment]
![image](https://user-images.githubusercontent.com/28520494/57683542-80bb2180-7666-11e9-9658-fb2081aadff5.png)
 这些需要PHP的可怎么办

**Comment by HFO4** [comment]
目前也没有比较好的办法，主要是...历史遗留问题。
临时的办法是开发时把开发服务器的静态文件URL写在模板文件里。
