### ISSUE TITLE
Add Traditional Chinese Option

### ISSUE THREAD

**Issue by conashin** [cloudreve/frontend#141]
Here are files that were translated to Traditional Chinese.
[https://github.com/conashin/frontend/tree/master/public/locales/zh-TW](https://github.com/conashin/frontend/tree/master/public/locales/zh-TW)

**Comment by HFO4** [comment]
Thanks! We will review and include those translations into main branch.

**Comment by HFO4** [comment]
Traditional Chinese will be included in 3.7.
