### ISSUE TITLE
前端Redux部分重构

### ISSUE THREAD

**Issue by SHITianhao** [cloudreve/frontend#15]
我在做前端Shift多选时发现一些问题，可以讨论一下。看能不能根据我的方案进行redux的改造。
1. [紧急] 引入[Redux thunk](https://github.com/reduxjs/redux-thunk), 可以做更复杂高级的Action Creator。第一可以更方便的加入复杂的UI逻辑比如shift多选，第二方便后期做到Component和Reducer的分离
    * [Redux Saga](https://github.com/redux-saga/redux-saga) 也不错，但是和现有代码兼容性比较差
2. [一般] 移除每个Page下面的Redux Store。多个Redux Store并不是作为隔离的最好办法，这样只会增加内存开销。可以通过Namespace的方式隔离每个Page
3. [长期] 尽量分离Component和Reducers。Reducer 包含各种业务逻辑判断，Component只根据State进行渲染。分离后UI更容易改造和更新，只需要替换Component而不用改变Reducer。同时reducer中的业务逻辑可以增加单元测试保证在升级中的业务逻辑一致

引入Redux Thunk的好处我们可以以Shift连续多选作为例子:
用户动作流程：
```
1. 按住Shift按钮
2. 点击起始文件
3. 保持Shift按钮，同时点击结束文件
4. App显示选中从起始文件到结束文件中间的所有文件
```
App状态变化
```
1. 按下Shift键，进入shift多选模式(shiftMode=true)
    * 用户松开Shift键，取消shift多选模式(shiftMode=false)
2. 点击起始文件，记录起始文件位置 (startFile = selectedFile)
    * 如果用户同时按住Control键不能进入Control模式
3. 点击下一个文件，记录结束文件位置  (endFile = selectedFile)。同时从AllFiles中取出从startFile 到endFile 中的所有文件加入到selectedFiles 中
```
2这个点Shift模式和普通点击模式很像，但是又有不同。
现有的选择文件逻辑,[这里](https://github.com/cloudreve/frontend/blob/master/src/component/FileManager/ObjectIcon.js#L109)
引入Redux thunk后, 将Select File 变成一个Action Creator 
```
function selectFile(file) {
  return (dispatch, getState) => {
    const { shiftMode } = getState();
    if (shiftMode) {
        dispatch(shiftSelectFile(file))
    } else {
       dispatch(selectSingleFile(file))
    }
  }
}

function selectSingleFile(file) {
// 现有选择逻辑保持一致
}

function shiftSelectFile(file) {
  return (dispatch, getState) => {
    const { startFile } = getState();
    if (!startFile) {
        dispatch(setStartFile(file))
    } else {
      // 选中从StartFile 到 file之间的所有文件
       dispatch(selectFilesFrom(startFile, file))
    }
  }
}
```

**Comment by HFO4** [comment]
非常感谢您的建议，下面是我的一点看法。
1. 我觉得可以引入。
2. 不是太清楚您的意思，目前的话是所有页面共用一个store的。`src/pages`下可能有这种情况，这个其实是老版本的残留目录，已经用不到了。
3. 这个可以以后慢慢来做，逐步抽离出来。

**Comment by SHITianhao** [comment]
OK，那我在我的下一个PR里会引入Redux Thunk.
第二点确实说的是`src/pages`下的文件。这个不用了就无所谓，是我不太清楚代码
