### ISSUE TITLE
重构reducer后产生的几个小问题

### ISSUE THREAD

**Issue by HFO4** [cloudreve/frontend#25]
1. 对于没有安装Redux Dev Tool 扩展的浏览器，` window.__REDUX_DEVTOOLS_EXTENSION__` 未定义，会抛出异常导致页面空白。
https://github.com/cloudreve/frontend/blob/35e10a562b612af03b8bac27a3a0dc67dfba16c1/src/index.js#L21
这个之前是没问题的，不知为何现在就出问题了。

2. 我尝试删去上一条的Devtool中间件后， reducer 分发时，似乎没考虑`@@redux/INIT`的特殊 action，导致这里抛出异常。
https://github.com/cloudreve/frontend/blob/35e10a562b612af03b8bac27a3a0dc67dfba16c1/src/redux/combineReducers.ts#L11
目测是因为之前 Redux Dev Toool 拦截处理了这个action，所以之前没出问题

**Comment by zjsth92** [comment]
第一个我也不是太清楚，我明天本地复现看下。
第二个我立刻提交一个PR，所有`@@`开头的都不做分发处理
