### ISSUE TITLE
针对该前端仓库v2版本的讨论

### ISSUE THREAD

**Issue by sky5454** [cloudreve/frontend#3]
首先，我不是本项目的开发人员，只是分享一些我的研究心得，以便于大家进行代码阅读和贡献

本前端仓库其实是从php项目[Cloudreve](https://github.com/cloudreve/Cloudreve)分离出来的，但估计由于时间不足或其他问题，此前端还保留了php的一些东西

如 `public/index.html` 里的 `{$变量名}` 其实是 php 的一个库 (thinkphp模板引擎) 的东西，将其静态化（即变成纯HTML+JS+CSS）后，等价于 `public/index_dev.html`
![image](https://user-images.githubusercontent.com/12370628/72275505-04e7fd80-3669-11ea-885b-b45f789348ac.png)

也就是说  `public/index.html` 其实是一个用来生成纯静态文件的模板
[ThinkPHP模板变量与常用标签](https://www.jianshu.com/p/13b2fc3f23d3)

 - 与此相关的 ISSUE
   - #1

**Comment by sky5454** [comment]
**Cloudreve 项目**中把大部分的js代码都写在了`<div id="root"></div>`之后，此仓库去除了 div 标签后的前端 JS 逻辑代码，以便于开发者使用。

如果您需要逻辑代码，建议参考 **Cloudreve 项目**里 `application/index/view` 目录下的 thinkphp 模板文件(后缀名为 .html)


详见 div 标签附近的注释

<hr><br><br><br>

另外，

**Comment by sky5454** [comment]
去Cloudreve后端仓库里找数据（一般在Model层），然后对**{$php对象变量名}**进行替换，可以得到可用的页面

![image](https://user-images.githubusercontent.com/12370628/72324523-1f13f100-36e6-11ea-8a2b-61920087cc1d.png)

**Comment by HFO4** [comment]
感谢整理。目前的模式是历史遗留问题，在V3版本中会将前后端彻底分离。

**Comment by sky5454** [comment]
> 
> 
> 感谢整理。目前的模式是历史遗留问题，在V3版本中会将前后端彻底分离。

你好，问一下V3的前端仓库什么时候出来。另外，其实建议完善一下开发文档，这样可以让更多的人参与进来。个人觉得你的这个项目是国内网盘里最好的了。
![image](https://user-images.githubusercontent.com/12370628/72325468-20deb400-36e8-11ea-8f86-b85a15763025.png)
