### ISSUE TITLE
monaco-editor-webpack-plugin 需要更新

### ISSUE THREAD

**Issue by topjohncian** [cloudreve/frontend#49]
monaco-editor-webpack-plugin 依赖需要更新

**Comment by topjohncian** [comment]
旧版本 yarn start 会报错 `Cannot find module vs/***`

**Comment by lsCoding666** [comment]
> 旧版本 yarn start 会报错 `Cannot find module vs/***`

出现了同样的错误，你的yarn版本是多少？ 上网查了貌似原因是monaco-editor-webpack-plugin 和 monaco-editor 的版本对应不上
![image](https://user-images.githubusercontent.com/73888354/152939280-155995c0-c417-4b73-8eb4-602fb9fd6ee1.png)
![image](https://user-images.githubusercontent.com/73888354/152939327-2224cc49-da99-43e0-94b5-f0938783c47d.png)
![image](https://user-images.githubusercontent.com/73888354/152939342-53e2ba56-533a-4f13-a2ba-23a5b845a40a.png)

**Comment by lsCoding666** [comment]
解决了 换回官方源就好了 很奇怪 淘宝不行
