### ISSUE TITLE
后期前端的一些想法

### ISSUE THREAD

**Issue by SHITianhao** [cloudreve/frontend#9]
1. 是否考虑使用蚂蚁的[ant design](https://ant.design/index-cn) 取代现有的Material？
   * 第一 Material 设计有点老了 ;) 主要现在不是很流行使用阴影。而阴影重叠感是material的一大特色
   * Material 的设计组件之间的pending太大，空间利用率比较低
   * AntD 很多组件设计的很好，比如上传文件的[Upload](https://ant.design/components/upload-cn/)。可以减少一些维护和开发的成本

2. 使用 prettier 等自动清理 Eslint warning
3. 使用TypeScript

后两点主要考虑多人协作开发

**Comment by HFO4** [comment]
@SHITianhao 重构的话在3.X版本内暂时不考虑，工作量还是太大。
Warning和TypeScript会在后续逐步解决应用。
